### ISSUE TITLE
Adding to READMEs

### ISSUE THREAD

**Issue by john-science** [terrapower/armicontrib-openmc#13]
I was thinking that adding two things to the README would be really helpful:

1. A link to the OpenMC install guide.
    a. Did you use this?  https://docs.openmc.org/en/stable/quickinstall.html
2. How to run your test case.
    a. I assume it's [this](https://github.com/terrapower/armicontrib-openmc/blob/develop/openmcdemo/__main__.py) pointing to [this](https://github.com/terrapower/armicontrib-openmc/blob/develop/openmcdemo/cli/runFFTF.py), but giving a command line makes it easier for people new to this project.

Forgive me if you think this is obvious.

**Comment by john-science** [comment]
I'm just thinking aloud here.

**Comment by AidanMcDonald** [comment]
Great suggestions. I will link to both the quick install and the more detailed page [https://docs.openmc.org/en/stable/usersguide/install.html] which I've found more useful.

Running the test case is definitely not obvious at the moment, so I'll add good instructions for that too.

**Comment by AidanMcDonald** [comment]
The requested changes are up. Let me know if what I've added is sufficient and makes sense.
