### ISSUE TITLE
Move away from TOX

### ISSUE THREAD

**Issue by john-science** [terrapower/armicontrib-openmc#17]
It appears no one is using TOX locally, and TOX is only used on CI.  This defeats the purpose of TOX entirely, so we might as well ditch it.

**Comment by john-science** [comment]
@AidanMcDonald Unless you're using TOX locally?

**Comment by AidanMcDonald** [comment]
I am not using TOX locally. It has been removed for now.

**Comment by john-science** [comment]
> I am not using TOX locally. It has been removed for now.

Yup, I no longer see it in your branch.  Thanks!
